export const rawLayerData = [
  {
    name: 'AIS masten',
    layer: {
      type: 'FeatureCollection',
      features: [
        {
          id: 1,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.899398, 52.4000991],
          },
          properties: {
            Locatienaam: 'Floating office',
          },
          category: 'Slimme verkeersinformatie',
          soort: 'Floating office',
          privacy: '',
          contact: 'ais-masten',
          longitude: 4.899398,
          latitude: 52.4000991,
        },
        {
          id: 2,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.9019353, 52.3657756],
          },
          properties: {
            Locatienaam: 'Walter Suskindbrug',
          },
          category: 'Slimme verkeersinformatie',
          soort: 'Walter Suskindbrug',
          privacy: '',
          contact: 'ais-masten',
          longitude: 4.9019353,
          latitude: 52.3657756,
        },
        {
          id: 3,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.9025651, 52.3621247],
          },
          properties: {
            Locatienaam: 'Amstelsluizen',
          },
          category: 'Slimme verkeersinformatie',
          soort: 'Amstelsluizen',
          privacy: '',
          contact: 'ais-masten',
          longitude: 4.9025651,
          latitude: 52.3621247,
        },
        {
          id: 4,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.9170739, 52.3400081],
          },
          properties: {
            Locatienaam: 'HQ Waternet',
          },
          category: 'Slimme verkeersinformatie',
          soort: 'HQ Waternet',
          privacy: '',
          contact: 'ais-masten',
          longitude: 4.9170739,
          latitude: 52.3400081,
        },
        {
          id: 5,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.8880951, 52.3602692],
          },
          properties: {
            Locatienaam: 'Pomphuis',
          },
          category: 'Slimme verkeersinformatie',
          soort: 'Pomphuis',
          privacy: '',
          contact: 'ais-masten',
          longitude: 4.8880951,
          latitude: 52.3602692,
        },
        {
          id: 6,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.8467078, 52.3388307],
          },
          properties: {
            Locatienaam: 'Nieuwe Meersluis',
          },
          category: 'Slimme verkeersinformatie',
          soort: 'Nieuwe Meersluis',
          privacy: '',
          contact: 'ais-masten',
          longitude: 4.8467078,
          latitude: 52.3388307,
        },
      ],
    },
    category: 'Slimme verkeersinformatie',
  },
  {
    name: 'Wagenparkscan',
    layer: {
      type: 'FeatureCollection',
      features: [
        {
          id: 1,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.8945537, 52.3578527],
          },
          properties: {
            Locatienummer: '01',
            Locatienaam: 'GASK-01-A-Stadhouderskade-O',
            Locatieadres: 'Stadhouderskade 86',
            Te_meten_rijstrook: '',
            Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
          },
          category: 'Camera',
          soort: 'GASK-01-A-Stadhouderskade-O',
          privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
          contact: 'wagenparkscan',
          longitude: 4.8945537,
          latitude: 52.3578527,
        },
        {
          id: 2,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.9071666, 52.3625765],
          },
          properties: {
            Locatienummer: '02',
            Locatienaam: 'GASK-02-A-Weesperstraat-N',
            Locatieadres: 'Weesperstraat 113',
            Te_meten_rijstrook: '',
            Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
          },
          category: 'Camera',
          soort: 'GASK-02-A-Weesperstraat-N',
          privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
          contact: 'wagenparkscan',
          longitude: 4.9071666,
          latitude: 52.3625765,
        },
        {
          id: 3,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.9064064, 52.3694364],
          },
          properties: {
            Locatienummer: '03',
            Locatienaam: 'GASK-03-A-Valkenburgerstraat-N',
            Locatieadres: 'Valkenburgerstraat',
            Te_meten_rijstrook: '',
            Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
          },
          category: 'Camera',
          soort: 'GASK-03-A-Valkenburgerstraat-N',
          privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
          contact: 'wagenparkscan',
          longitude: 4.9064064,
          latitude: 52.3694364,
        },
        {
          id: 4,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.9107997, 52.3568955],
          },
          properties: {
            Locatienummer: '04A',
            Locatienaam: 'GASK-04-A-Wibautstraat-N',
            Locatieadres: 'Wibautstraat 45',
            Te_meten_rijstrook: '',
            Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
          },
          category: 'Camera',
          soort: 'GASK-04-A-Wibautstraat-N',
          privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
          contact: 'wagenparkscan',
          longitude: 4.9107997,
          latitude: 52.3568955,
        },
        {
          id: 5,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.9102458, 52.3571118],
          },
          properties: {
            Locatienummer: '04B',
            Locatienaam: 'GASK-04-B-Wibautstraat-Z',
            Locatieadres: 'Wibautstraat 45',
            Te_meten_rijstrook: '',
            Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
          },
          category: 'Camera',
          soort: 'GASK-04-B-Wibautstraat-Z',
          privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
          contact: 'wagenparkscan',
          longitude: 4.9102458,
          latitude: 52.3571118,
        },
        {
          id: 6,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.8959646, 52.3701274],
          },
          properties: {
            Locatienummer: '',
            Locatienaam: 'Oudezijde',
            Locatieadres: '',
            Te_meten_rijstrook: '',
            Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/artikel-2/',
          },
          category: 'Camera',
          soort: 'Oudezijde',
          privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/artikel-2/',
          contact: 'wagenparkscan',
          longitude: 4.8959646,
          latitude: 52.3701274,
        },
        {
          id: 7,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [4.8959695, 52.3701405],
          },
          properties: {
            Locatienummer: '',
            Locatienaam: 'Rusland',
            Locatieadres: 'Rusland 6 ',
            Te_meten_rijstrook: 'Linker rijstrook',
            Privacyverklaring: 'www.amsterdam.nl/privacy/specifieke/privacyverklarigen-b/artikel-2/',
          },
          category: 'Camera',
          soort: 'Rusland',
          privacy: 'www.amsterdam.nl/privacy/specifieke/privacyverklarigen-b/artikel-2/',
          contact: 'wagenparkscan',
          longitude: 4.8959695,
          latitude: 52.3701405,
        },
      ],
    },
    category: 'Camera',
  },
];

export const layerData = {
  'Slimme verkeersinformatie': {
    type: 'FeatureCollection',
    name: 'Slimme verkeersinformatie',
    crs: { type: 'name', properties: { name: 'urn:ogc:def:crs:OGC:1.3:CRS84' } },
    features: [
      {
        id: 1,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.899398, 52.4000991] },
        properties: { Locatienaam: 'Floating office' },
        category: 'Slimme verkeersinformatie',
        soort: 'Floating office',
        privacy: '',
        contact: 'ais-masten',
        longitude: 4.899398,
        latitude: 52.4000991,
      },
      {
        id: 2,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.9019353, 52.3657756] },
        properties: { Locatienaam: 'Walter Suskindbrug' },
        category: 'Slimme verkeersinformatie',
        soort: 'Walter Suskindbrug',
        privacy: '',
        contact: 'ais-masten',
        longitude: 4.9019353,
        latitude: 52.3657756,
      },
      {
        id: 3,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.9025651, 52.3621247] },
        properties: { Locatienaam: 'Amstelsluizen' },
        category: 'Slimme verkeersinformatie',
        soort: 'Amstelsluizen',
        privacy: '',
        contact: 'ais-masten',
        longitude: 4.9025651,
        latitude: 52.3621247,
      },
      {
        id: 4,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.9170739, 52.3400081] },
        properties: { Locatienaam: 'HQ Waternet' },
        category: 'Slimme verkeersinformatie',
        soort: 'HQ Waternet',
        privacy: '',
        contact: 'ais-masten',
        longitude: 4.9170739,
        latitude: 52.3400081,
      },
      {
        id: 5,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.8880951, 52.3602692] },
        properties: { Locatienaam: 'Pomphuis' },
        category: 'Slimme verkeersinformatie',
        soort: 'Pomphuis',
        privacy: '',
        contact: 'ais-masten',
        longitude: 4.8880951,
        latitude: 52.3602692,
      },
      {
        id: 6,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.8467078, 52.3388307] },
        properties: { Locatienaam: 'Nieuwe Meersluis' },
        category: 'Slimme verkeersinformatie',
        soort: 'Nieuwe Meersluis',
        privacy: '',
        contact: 'ais-masten',
        longitude: 4.8467078,
        latitude: 52.3388307,
      },
    ],
  },
  Camera: {
    type: 'FeatureCollection',
    name: 'Camera',
    crs: { type: 'name', properties: { name: 'urn:ogc:def:crs:OGC:1.3:CRS84' } },
    features: [
      {
        id: 1,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.8945537, 52.3578527] },
        properties: {
          Locatienummer: '01',
          Locatienaam: 'GASK-01-A-Stadhouderskade-O',
          Locatieadres: 'Stadhouderskade 86',
          Te_meten_rijstrook: '',
          Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
        },
        category: 'Camera',
        soort: 'GASK-01-A-Stadhouderskade-O',
        privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
        contact: 'wagenparkscan',
        longitude: 4.8945537,
        latitude: 52.3578527,
      },
      {
        id: 2,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.9071666, 52.3625765] },
        properties: {
          Locatienummer: '02',
          Locatienaam: 'GASK-02-A-Weesperstraat-N',
          Locatieadres: 'Weesperstraat 113',
          Te_meten_rijstrook: '',
          Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
        },
        category: 'Camera',
        soort: 'GASK-02-A-Weesperstraat-N',
        privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
        contact: 'wagenparkscan',
        longitude: 4.9071666,
        latitude: 52.3625765,
      },
      {
        id: 3,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.9064064, 52.3694364] },
        properties: {
          Locatienummer: '03',
          Locatienaam: 'GASK-03-A-Valkenburgerstraat-N',
          Locatieadres: 'Valkenburgerstraat',
          Te_meten_rijstrook: '',
          Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
        },
        category: 'Camera',
        soort: 'GASK-03-A-Valkenburgerstraat-N',
        privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
        contact: 'wagenparkscan',
        longitude: 4.9064064,
        latitude: 52.3694364,
      },
      {
        id: 4,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.9107997, 52.3568955] },
        properties: {
          Locatienummer: '04A',
          Locatienaam: 'GASK-04-A-Wibautstraat-N',
          Locatieadres: 'Wibautstraat 45',
          Te_meten_rijstrook: '',
          Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
        },
        category: 'Camera',
        soort: 'GASK-04-A-Wibautstraat-N',
        privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
        contact: 'wagenparkscan',
        longitude: 4.9107997,
        latitude: 52.3568955,
      },
      {
        id: 5,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.9102458, 52.3571118] },
        properties: {
          Locatienummer: '04B',
          Locatienaam: 'GASK-04-B-Wibautstraat-Z',
          Locatieadres: 'Wibautstraat 45',
          Te_meten_rijstrook: '',
          Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
        },
        category: 'Camera',
        soort: 'GASK-04-B-Wibautstraat-Z',
        privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/wagenparkscan/',
        contact: 'wagenparkscan',
        longitude: 4.9102458,
        latitude: 52.3571118,
      },
      {
        id: 6,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.8959646, 52.3701274] },
        properties: {
          Locatienummer: '',
          Locatienaam: 'Oudezijde',
          Locatieadres: '',
          Te_meten_rijstrook: '',
          Privacyverklaring: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/artikel-2/',
        },
        category: 'Camera',
        soort: 'Oudezijde',
        privacy: 'https://www.amsterdam.nl/privacy/specifieke/privacyverklaringen-b/artikel-2/',
        contact: 'wagenparkscan',
        longitude: 4.8959646,
        latitude: 52.3701274,
      },
      {
        id: 7,
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [4.8959695, 52.3701405] },
        properties: {
          Locatienummer: '',
          Locatienaam: 'Rusland',
          Locatieadres: 'Rusland 6 ',
          Te_meten_rijstrook: 'Linker rijstrook',
          Privacyverklaring: 'www.amsterdam.nl/privacy/specifieke/privacyverklarigen-b/artikel-2/',
        },
        category: 'Camera',
        soort: 'Rusland',
        privacy: 'www.amsterdam.nl/privacy/specifieke/privacyverklarigen-b/artikel-2/',
        contact: 'wagenparkscan',
        longitude: 4.8959695,
        latitude: 52.3701405,
      },
    ],
  },
};

